trigger:
  branches:
    include:
      - master
      - feature/*

variables:
  - group: Sonar

pool:
  name: MySelfHostedPool

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - script: |
              java -version
              mvn -version
            displayName: 'Verify Java and Maven'

          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package spring-boot:repackage'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              codeCoverageToolOption: 'JaCoCo'
            env:
              SONAR_TOKEN: $(SONAR_TOKEN)

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'target/devops-demo-0.0.1-SNAPSHOT.jar'
              artifactName: 'app-artifact'
              publishLocation: 'Container'

  - stage: Deliver
    dependsOn: Build
    jobs:
      - job: DeliverJob
        steps:
          - download: current
            artifact: app-artifact

          - script: echo "Delivering the artifact..."
            displayName: 'Deliver Step'

  - stage: DeployToDev
    dependsOn: Deliver
    jobs:
      - job: DeployJob
        steps:
          - download: current
            artifact: app-artifact

          - script: |
              echo "Running the application on port 8085..."
              start /B java -jar "$(Pipeline.Workspace)\app-artifact\devops-demo-0.0.1-SNAPSHOT.jar" --server.port=8085
              timeout /T 10 > NUL
            displayName: 'Run app on port 8085'

          - script: |
              echo "Verifying the application is running..."
              curl --fail http://localhost:8085/status || (echo "App failed to start" && exit 1)
            displayName: 'Check app status'
