trigger:
  branches:
    include:
      - main
      - feature/*

variables:
  - group: Sonar

pool:
  name: MySelfHostedPool  # Use your self-hosted agent pool

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - script: |
              java -version
              mvn -version
            displayName: 'Verify Java and Maven'
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              codeCoverageToolOption: 'JaCoCo'
              sonarQubeRunAnalysis: true
              sqMavenPluginVersionChoice: 'latest'
            env:
              SONAR_TOKEN: $(SONAR_TOKEN)  # Using the environment variable securely
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: 'target/devops-demo-0.0.1-SNAPSHOT.jar'
              artifactName: 'app-artifact'
              publishLocation: 'Container'

  # Rest of your stages...
